--FIRST_HALF H, ICECREAM_INFO I
--아이스크림 맛
--FLAVOR
--총주문량 > 3000
--주성분 = 과일 INGREDIENT_TYPE = 'fruit_based'
--정렬 : 총주문량 역순
SELECT
    H.FLAVOR
FROM FIRST_HALF H INNER JOIN ICECREAM_INFO I
ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER > 3000
AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY H.TOTAL_ORDER DESC;
    