-- USED_GOODS_BOARD B
-- USED_GOODS_REPLY R
-- 게시글 제목 // B - TITLE
-- , 게시글 ID // B - BOARD_ID
-- , 댓글 ID // R - REPLY_ID
-- , 댓글 작성자 ID // R - WRITER_ID
-- , 댓글 내용 // R - CONTENTS
-- , 댓글 작성일 // R - CREATED_DATE
SELECT
    B.TITLE
    , B.BOARD_ID
    , R.REPLY_ID
    , R.WRITER_ID
    , R.CONTENTS
    , TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY R.CREATED_DATE, B.TITLE ASC;